from __future__ import annotations

from pathlib import Path

import typer

app = typer.Typer(
    help="BIDSFlow: a task-first CLI for BIDS workflow logistics.",
    no_args_is_help=True,
)

SCAFFOLD_DIRECTORIES = (
    Path("sourcedata"),
    Path("sourcedata") / "raw",
    Path("derivatives"),
    Path("work"),
    Path("logs"),
    Path("state"),
)


def _toml_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _render_project_config(project_name: str) -> str:
    return "\n".join(
        (
            "# Generated by `bidsflow init`.",
            "# Review before first use:",
            "# - adjust [project].name if you want a clearer project label",
            "# - adjust [paths] if your project layout differs from this scaffold",
            "",
            "[project]",
            f"name = {_toml_string(project_name)}",
            'root = "."',
            "",
            "[paths]",
            'source_root = "sourcedata"',
            'raw_bids_root = "sourcedata/raw"',
            'derivatives_root = "derivatives"',
            'work_root = "work"',
            'logs_root = "logs"',
            'state_root = "state"',
            "",
        )
    )


def _default_project_name(directory: Path) -> str:
    return directory.resolve().name or "BIDSFlow project"


def _validate_config_name(config_name: str) -> str:
    candidate = Path(config_name)
    if config_name in {"", ".", ".."} or candidate.name != config_name:
        raise typer.BadParameter("Config name must be a filename, not a path.")
    return config_name


@app.callback()
def main() -> None:
    """BIDSFlow: task-first CLI for BIDS workflow logistics."""


@app.command()
def init(
    directory: Path = typer.Argument(
        Path("."),
        file_okay=False,
        help="Directory where the project scaffold should be created.",
    ),
    name: str | None = typer.Option(
        None,
        "--name",
        help="Project name to write into the generated config.",
    ),
    config_name: str = typer.Option(
        "bidsflow.toml",
        "--config-name",
        help="Filename for the generated config.",
    ),
    force: bool = typer.Option(
        False,
        "--force",
        help="Overwrite the generated config if it already exists.",
    ),
) -> None:
    """Initialize a minimal BIDSFlow project scaffold."""
    config_name = _validate_config_name(config_name)
    target_directory = directory.resolve()

    if target_directory.exists() and not target_directory.is_dir():
        typer.echo(f"Target path is not a directory: {target_directory}", err=True)
        raise typer.Exit(code=2)

    config_path = target_directory / config_name
    if config_path.exists() and not force:
        typer.echo(
            f"Refusing to overwrite existing config: {config_path}. Use --force to overwrite it.",
            err=True,
        )
        raise typer.Exit(code=2)

    target_directory.mkdir(parents=True, exist_ok=True)
    for relative_path in SCAFFOLD_DIRECTORIES:
        (target_directory / relative_path).mkdir(parents=True, exist_ok=True)

    project_name = name or _default_project_name(target_directory)
    config_path.write_text(_render_project_config(project_name), encoding="utf-8", newline="\n")

    typer.echo(f"Initialized BIDSFlow project at {target_directory}")
    typer.echo(f"Config: {config_path}")


if __name__ == "__main__":
    app()
