from __future__ import annotations

from pathlib import Path

import typer

from .heudiconv import (
    HeudiconvManifestError,
    HeudiconvSkeletonError,
    format_command,
    plan_manifest,
    plan_skeleton,
    run_manifest,
    run_skeleton,
)
from .project import find_project_config, load_project_context

app = typer.Typer(
    help="BIDSFlow: a task-first CLI for BIDS workflow logistics.",
    no_args_is_help=True,
)
heudiconv_app = typer.Typer(help="Managed HeuDiConv workflow commands.")
app.add_typer(heudiconv_app, name="heudiconv")

DEFAULT_LAYOUT_DIRECTORIES = (
    Path("sourcedata"),
    Path("sourcedata") / "raw",
    Path("derivatives"),
    Path("work"),
    Path("logs"),
    Path("state"),
)


def _toml_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _render_project_config(project_name: str) -> str:
    return "\n".join(
        (
            "# Generated by `bidsflow init`.",
            "# Review before first use:",
            "# - adjust [project].name if you want a clearer project label",
            "# - adjust [paths] if your project layout differs from this scaffold",
            "# - uncomment [heudiconv] if you need a wrapper or Singularity launcher",
            "",
            "[project]",
            f"name = {_toml_string(project_name)}",
            'root = "."',
            "",
            "[paths]",
            'source_root = "sourcedata"',
            'raw_bids_root = "sourcedata/raw"',
            'derivatives_root = "derivatives"',
            'work_root = "work"',
            'logs_root = "logs"',
            'state_root = "state"',
            "",
            "# Optional HeuDiConv launcher override.",
            "# Uncomment and edit this block if HeuDiConv is launched through a wrapper or container.",
            "# [heudiconv]",
            '# launcher = ["heudiconv"]',
            '# launcher = ["singularity", "run", "/containers/heudiconv.sif"]',
            "",
        )
    )


def _default_project_name(directory: Path) -> str:
    return directory.resolve().name or "BIDSFlow project"


def _validate_config_name(config_name: str) -> str:
    candidate = Path(config_name)
    if config_name in {"", ".", ".."} or candidate.name != config_name:
        raise typer.BadParameter("Config name must be a filename, not a path.")
    return config_name


@app.callback()
def main() -> None:
    """BIDSFlow: task-first CLI for BIDS workflow logistics."""


@app.command()
def init(
    directory: Path = typer.Argument(
        Path("."),
        file_okay=False,
        help="Directory where the project scaffold should be created.",
    ),
    name: str | None = typer.Option(
        None,
        "--name",
        help="Project name to write into the generated config.",
    ),
    config_name: str = typer.Option(
        "bidsflow.toml",
        "--config-name",
        help="Filename for the generated config.",
    ),
    force: bool = typer.Option(
        False,
        "--force",
        help="Overwrite the generated config if it already exists.",
    ),
    make_dirs: bool = typer.Option(
        False,
        "--make-dirs",
        help="Create the default project directories described by the generated config.",
    ),
) -> None:
    """Initialize a minimal BIDSFlow project scaffold."""
    config_name = _validate_config_name(config_name)
    target_directory = directory.resolve()

    if target_directory.exists() and not target_directory.is_dir():
        typer.echo(f"Target path is not a directory: {target_directory}", err=True)
        raise typer.Exit(code=2)

    config_path = target_directory / config_name
    if config_path.exists() and not force:
        typer.echo(
            f"Refusing to overwrite existing config: {config_path}. Use --force to overwrite it.",
            err=True,
        )
        raise typer.Exit(code=2)

    target_directory.mkdir(parents=True, exist_ok=True)

    project_name = name or _default_project_name(target_directory)
    config_path.write_text(_render_project_config(project_name), encoding="utf-8", newline="\n")

    if make_dirs:
        for relative_path in DEFAULT_LAYOUT_DIRECTORIES:
            (target_directory / relative_path).mkdir(parents=True, exist_ok=True)

    typer.echo(f"Initialized BIDSFlow project at {target_directory}")
    typer.echo(f"Config: {config_path}")


@heudiconv_app.command("skeleton")
def heudiconv_skeleton(
    sample_paths: list[Path] = typer.Argument(
        ...,
        exists=False,
        help="One or more representative DICOM sample paths used to generate starter HeuDiConv outputs.",
    ),
    config: Path | None = typer.Option(
        None,
        "--config",
        help="Path to bidsflow.toml. Defaults to the nearest project config.",
    ),
    reset: bool = typer.Option(
        False,
        "--reset",
        help="Regenerate skeleton outputs after clearing prior HeuDiConv state.",
    ),
    dry_run: bool = typer.Option(
        False,
        "--dry-run",
        help="Show the managed command and planned output locations without running it.",
    ),
) -> None:
    """Generate a HeuDiConv skeleton from representative sample paths."""
    try:
        config_path = find_project_config(config, Path.cwd())
        context = load_project_context(config_path)
        plan = plan_skeleton(context, sample_paths)
    except (HeudiconvSkeletonError, ValueError) as exc:
        typer.echo(str(exc), err=True)
        raise typer.Exit(code=2) from exc

    if dry_run:
        if len(plan.units) == 1 and plan.units[0].session_label is None:
            unit = plan.units[0]
            typer.echo("Planned HeuDiConv skeleton strategy: single-directory skeleton")
            typer.echo(
                f"Temporary subject for skeleton: {unit.subject_label}"
            )
            typer.echo(format_command(unit.initial_command))
        else:
            typer.echo(
                f"Planned HeuDiConv skeleton strategy: split {len(plan.units)} directories into "
                "single-directory session units"
            )
            for unit in plan.units:
                typer.echo(
                    f"{unit.unit_name}: sample={unit.sample_path} "
                    f"subject={unit.subject_label} session={unit.session_label}"
                )
                typer.echo(format_command(unit.initial_command))
        typer.echo(f"Config: {config_path}")
        typer.echo(f"Sample paths: {len(plan.sample_paths)}")
        typer.echo(f"Skeleton work root: {plan.skeleton_work_root}")
        typer.echo(f"Heuristic: {plan.heuristic_path}")
        typer.echo(f"DICOM inventories: {plan.dicominfo_root}")
        typer.echo(f"State: {plan.skeleton_state_path}")
        typer.echo(f"Log: {plan.log_path}")
        return

    try:
        result = run_skeleton(context, plan, reset=reset)
    except HeudiconvSkeletonError as exc:
        typer.echo(str(exc), err=True)
        raise typer.Exit(code=2) from exc

    typer.echo("Prepared HeuDiConv skeleton outputs.")
    typer.echo(f"Skeleton units: {len(result.unit_results)}")
    typer.echo(f"Skeleton work root: {plan.skeleton_work_root}")
    typer.echo(f"Heuristic: {result.heuristic_path}")
    typer.echo(f"DICOM inventories: {result.dicominfo_root} ({len(result.dicominfo_paths)} files)")
    typer.echo(f"State: {result.skeleton_state_path}")
    typer.echo(f"Log: {result.log_path}")
    typer.echo(
        "Next: review and edit the heuristic. Manifest can be prepared before or after "
        "skeleton, but convert will need both a confirmed manifest and a reviewed heuristic."
    )


@heudiconv_app.command("manifest")
def heudiconv_manifest(
    source_root: Path = typer.Argument(
        ...,
        exists=False,
        file_okay=False,
        dir_okay=True,
        help="Root directory whose immediate child directories should be listed in the manifest.",
    ),
    config: Path | None = typer.Option(
        None,
        "--config",
        help="Path to bidsflow.toml. Defaults to the nearest project config.",
    ),
    subject_regex: str | None = typer.Option(
        None,
        "--subject-regex",
        help="Optional regex applied to each source directory name to fill subject_raw.",
    ),
    session_regex: str | None = typer.Option(
        None,
        "--session-regex",
        help="Optional regex applied to each source directory name to fill session_raw.",
    ),
    reset: bool = typer.Option(
        False,
        "--reset",
        help="Regenerate the manifest after clearing prior manifest state.",
    ),
    dry_run: bool = typer.Option(
        False,
        "--dry-run",
        help="Show the planned manifest outputs without writing files.",
    ),
) -> None:
    """Enumerate source directories into a reviewable HeuDiConv manifest."""
    try:
        config_path = find_project_config(config, Path.cwd())
        context = load_project_context(config_path)
        plan = plan_manifest(
            context,
            source_root,
            subject_regex=subject_regex,
            session_regex=session_regex,
        )
    except (HeudiconvManifestError, ValueError) as exc:
        typer.echo(str(exc), err=True)
        raise typer.Exit(code=2) from exc

    if dry_run:
        typer.echo("Planned HeuDiConv manifest generation.")
        typer.echo(f"Config: {config_path}")
        typer.echo(f"Source root: {plan.source_root}")
        typer.echo(f"Entries discovered: {len(plan.entries)}")
        typer.echo(f"Manifest: {plan.manifest_path}")
        typer.echo(f"State: {plan.manifest_state_path}")
        typer.echo("Links: not created by manifest; convert will materialize temporary links if needed.")
        if plan.subject_regex is None and plan.session_regex is None:
            typer.echo("Extraction: no regex provided; subject/session columns will be left blank.")
        else:
            typer.echo(
                f"Extraction: subject_regex={plan.subject_regex!r} "
                f"session_regex={plan.session_regex!r}"
            )
        return

    try:
        result = run_manifest(context, plan, reset=reset)
    except HeudiconvManifestError as exc:
        typer.echo(str(exc), err=True)
        raise typer.Exit(code=2) from exc

    typer.echo("Wrote HeuDiConv manifest.")
    typer.echo(f"Entries: {result.entry_count}")
    typer.echo(f"Manifest: {result.manifest_path}")
    typer.echo(f"State: {result.manifest_state_path}")
    typer.echo(
        "Next: review manifest.tsv, then decide whether to fill labels manually or add "
        "explicit extraction rules. Skeleton may happen before or after manifest, but "
        "convert will materialize any temporary links it needs from the confirmed manifest."
    )


@heudiconv_app.command("convert")
def heudiconv_convert(
    dry_run: bool = typer.Option(
        False,
        "--dry-run",
        help="Reserved for the future managed convert step.",
    ),
) -> None:
    """Run the managed HeuDiConv conversion step."""
    _ = dry_run
    typer.echo(
        "heudiconv convert is not implemented yet. Edit code/heudiconv/heuristic.py first; "
        "the managed convert step is the next planned slice.",
        err=True,
    )
    raise typer.Exit(code=1)


if __name__ == "__main__":
    app()

